//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da scarabeo.rc
//
#define IDD_DIALOG1                     101
#define IDB_TAVOLAGIOCO                 103
#define IDB_A                           105
#define IDB_B                           106
#define IDB_C                           107
#define IDB_D                           108
#define IDB_E                           109
#define IDB_F                           110
#define IDB_G                           111
#define IDB_H                           112
#define IDB_I                           113
#define IDB_J                           115
#define IDB_K                           116
#define IDB_L                           117
#define IDB_M                           118
#define IDB_N                           119
#define IDB_O                           120
#define IDB_P                           121
#define IDB_Q                           122
#define IDB_R                           123
#define IDB_S                           124
#define IDB_T                           125
#define IDB_U                           126
#define IDB_V                           127
#define IDB_X                           128
#define IDB_Y                           129
#define IDB_Z                           130
#define IDB_1L                          132
#define IDB_3L                          133
#define IDB_2P                          134
#define IDB_2L                          135
#define IDB_3P                          137
#define IDB_SCARABEO                    138
#define IDB_W                           139
#define IDI_APP                         140
#define IDI_ICON1                       142
#define IDR_MENU1                       143
#define IDI_SMALL                       144
#define IDD_DIALOG2                     145
#define IDI_SETUP                       145
#define IDR_ACCELERATOR1                146
#define IDD_DIALOG3                     147
#define IDB_TSC                         148
#define IDD_DIALOG4                     149
#define IDB_VUOTA                       150
#define IDB_CIFRA4                      151
#define IDB_CIFRA3                      152
#define IDB_CIFRA2                      153
#define IDB_CIFRA1                      154
#define IDB_CIFRA0                      155
#define IDB_CIFRA7                      156
#define IDB_CIFRA8                      157
#define IDB_CIFRA9                      158
#define IDB_BITMAP10                    159
#define IDB_BITMAP11                    160
#define IDB_CIFRA5                      163
#define IDB_COMPUTER                    164
#define IDB_CIFRA6                      166
#define IDB_SEGNAPUNTI                  167
#define IDB_MAN                         168
#define IDD_DIALOG5                     169
#define IDD_DIALOG6                     170
#define IDB_TG_LUM                      172
#define IDB_TG_OMBRA                    173
#define IDB_TG_PASSA                    174
#define IDB_DORSO                       175
#define IDB_SCARABEO1                   176
#define IDB_BITMAP1                     177
#define IDB_TG_BN                       178
#define IDB_BITMAP2                     179
#define IDB_FIRMA                       181
#define IDB_SCARABOK                    182
#define IDD_DIALOG1_old                 188
#define IDD_DIALOG5_old                 196
#define IDC_EDIT1                       1000
#define IDC_NUOVO                       1001
#define IDC_EDIT2                       1002
#define IDC_BUTTON1                     1004
#define IDC_START                       1006
#define IDC_CONFERMA                    1007
#define IDC_PUNTI1                      1008
#define IDC_PUNTI2                      1009
#define IDC_ANNULLA                     1010
#define IDC_EDIT_DIZ                    1011
#define IDC_CALCOLA                     1012
#define IDC_SALVA                       1013
#define IDC_RIPRISTINA                  1014
#define IDC_MYHELP                      1015
#define IDC_CHECK_TESSERE               1016
#define IDC_CHECK_IDEE                  1017
#define IDC_CHECK_VAL                   1018
#define IDC_LEFT                        1019
#define IDC_DEMO                        1020
#define IDC_RADIO1                      1020
#define IDC_RADIO2                      1021
#define IDC_HELPME                      1021
#define IDC_TESTME                      1022
#define IDC_ORIG                        1022
#define IDC_A                           1023
#define IDC_RIFIUTA                     1023
#define IDC_E                           1024
#define IDC_FAI_SILENZIO                1024
#define IDC_I                           1025
#define IDC_O                           1026
#define IDC_INS                         1027
#define IDC_SOS                         1028
#define IDC_CAN                         1029
#define IDC_RUOTA                       1029
#define IDC_LIST                        1030
#define IDC_DEMOX                       1031
#define IDC_COMBO_SEARCH                1032
#define IDC_AST                         1033
#define IDC_PINT                        1034
#define IDC_ICS                         1035
#define IDC_MESCOLA                     1035
#define IDC_STATIC_BOARD                1037
#define ID__ITALIANO                    40001
#define ID__ENGLISH                     40002
#define ID_MENU_ITALIANO                40003
#define ID_MENU_ENGLISH                 40004
#define IDM_ESCAPE                      40007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
